<a href="https://colab.research.google.com/github/maverickNerd/MachineLearning/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Importing Numpy**

In [ ]:
import numpy as np

**Creating arrays**

In [ ]:
np.zeros(10, np.int8)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [ ]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.full(10,2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [ ]:
np.repeat(5, 10)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [ ]:
np.repeat([[10, 5], [6, 3]], [2, 3], axis=0)

array([[10,  5],
       [10,  5],
       [ 6,  3],
       [ 6,  3],
       [ 6,  3]])

In [ ]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [ ]:
a[2] = 100
a

array([  1,   2, 100,   4,   5])

In [ ]:
np.arange(3, 10, 2)

array([3, 5, 7, 9])

In [ ]:
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

**Multi-dementional arrays**

In [ ]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
zeros = np.zeros((5, 2), dtype=np.int32)
zeros

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int32)

In [ ]:
print(zeros.shape)

(5, 2)


In [ ]:
np.ones((5,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
n = np.array([
    [1,2, 3],
    [2,3, 4],
    [3,4, 5]
])
n

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [ ]:
numbers = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
numbers = np.array(numbers)

In [ ]:
numbers[0,2]

3

In [ ]:
numbers[0,2] = 10
numbers

array([[ 1,  2, 10],
       [ 4,  5,  6],
       [ 7,  8,  9]])

**Assignment: use a tuple (row index, column index)**

In [ ]:
n[1, 0] = 20
n

array([[ 1,  2,  3],
       [20,  3,  4],
       [ 3,  4,  5]])

**Row overwrite**

In [ ]:
n[2] = [1,2,2]
n

array([[1, 1, 2],
       [1, 1, 2],
       [1, 2, 2]])

**Slicing: getting a column:**

In [ ]:
numbers[:, 1]

array([2, 5, 8])

**Column Overwrite**

In [ ]:
n[:, 2] = [0, 1, 2]
n

array([[0, 1, 0],
       [0, 1, 1],
       [1, 2, 2]])

**Randomly generated arrays**

**Uniform random numbers between 0 and 1 of shape (5, 2):**

In [ ]:
np.random.rand(5, 2)

array([[0.53560417, 0.95374223],
       [0.54420816, 0.08209492],
       [0.3663424 , 0.8508505 ],
       [0.40627504, 0.02720237],
       [0.24717724, 0.06714437]])

**Set seed for reproducibility:**

In [ ]:
np.random.seed(2)

**Random integers between 0 and 99 (100 is not included)**

In [ ]:
np.random.randint(low=0, high=100, size = (2,5))

array([[96, 16, 55, 21, 43],
       [93, 80, 40, 70, 74]])

**Element-wise operations**

In [ ]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])


**Every item in the array is multiplied by 5:**

In [ ]:
a * 5

array([ 0,  5, 10, 15, 20])

In [ ]:
b = (10 + (a * 2)) ** 2 / 100

In [ ]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [ ]:
n = a/b +10
n

array([10.        , 10.69444444, 11.02040816, 11.171875  , 11.2345679 ])

**Rounding the numbers to 4th digit:**

In [ ]:
n.round(4)

array([10.    , 10.6944, 11.0204, 11.1719, 11.2346])

Two ways to square each element:


*   element-wise multiplication with itself
*   the power operator (**) 




In [ ]:
n = np.random.rand(3).round(2)
n

array([0.57, 0.39, 0.93])

In [ ]:
square = n * n
square.round(2)

array([0.32, 0.15, 0.86])

In [ ]:
square = n ** 2
square. round(2)

array([0.32, 0.15, 0.86])

Other element-wise operations:

* exp
* log
* sqrt

In [ ]:
np.exp(n)

array([1.76826705, 1.47698079, 2.53450918])

In [ ]:
np.log(n)

array([-0.56211892, -0.94160854, -0.07257069])

In [ ]:
np.sqrt(n)

array([0.75498344, 0.6244998 , 0.96436508])

**Comparison operations**

In [ ]:
a

array([0, 1, 2, 3, 4])

In [ ]:
a > b

array([False, False,  True,  True,  True])

In [ ]:
a >= 2

array([False, False,  True,  True,  True])

In [ ]:
a[a>b]

array([2, 3, 4])

**Logical operations**

In [ ]:
pred1 = np.random.rand(3) >= 0.3

In [ ]:
pred2 = np.random.rand(3) >= 0.4

In [ ]:
pred1 & pred2

array([False, False,  True])

In [ ]:
pred1 | pred2

array([False,  True,  True])

**Summarizing operations**

Summarizing operations process and array and return a single number

In [ ]:
np.random.seed(2)
pred = np.random.rand(3).round(2)
pred_sum = pred.sum()

print(pred)
print(pred_sum)

[0.44 0.03 0.55]
1.02


In [ ]:
print('min = %.2f' % pred.min())
print('mean = %.2f' % pred.mean())
print('max = %.2f' % pred.max())
print('std = %.2f' % pred.std())

min = 0.03
mean = 0.34
max = 0.55
std = 0.22


In [ ]:
a.std()

1.4142135623730951

In [ ]:
a.min()

0

But we can specify the axis along which we apply the summarizing operation

* axis=1 - apply to each rows
* axis=0 - apply to each column

In [ ]:
np.random.seed(2)
matrix = np.random.rand(4, 3).round(2)
matrix

array([[0.44, 0.03, 0.55],
       [0.44, 0.42, 0.33],
       [0.2 , 0.62, 0.3 ],
       [0.27, 0.62, 0.53]])

In [ ]:
matrix.max()

0.62

In [ ]:
matrix.max(axis=1)

array([0.55, 0.44, 0.62, 0.62])

In [ ]:
matrix.max(axis=0)

array([0.44, 0.62, 0.55])

In [ ]:
matrix.sum(axis=1)

array([1.02, 1.19, 1.12, 1.42])

**Sorting**

In [ ]:
np.random.seed(2)
pred = np.random.rand(4).round(2)
pred

array([0.44, 0.03, 0.55, 0.44])

Creates a new array

In [ ]:
np.sort(pred)

array([0.03, 0.44, 0.44, 0.55])

In [ ]:
pred

array([0.44, 0.03, 0.55, 0.44])

Sorts in place:

In [ ]:
pred.sort()

In [ ]:
pred

array([0.03, 0.44, 0.44, 0.55])

Argsort - instead of sorting, return the indexes of the array in sorted order

In [ ]:
np.random.seed(2)
pred = np.random.rand(4).round(2)
pred

array([0.44, 0.03, 0.55, 0.44])

In [ ]:
idx = pred.argsort()
idx

array([1, 0, 3, 2])

In [ ]:
pred[idx]

array([0.03, 0.44, 0.44, 0.55])

**Reshaping**

The shape of an array cound be changed but number of rows x columns should be equal to the total number of elements




In [ ]:
rng = np.arange(12)
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
rng.shape

(12,)

In [ ]:
rng.reshape(3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
rng.reshape(3, 4, order='F')

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

Putting mulitple arrays together:

* concatenate
* hstack
* vstack
* column_stack

In [ ]:
vec = np.arange(3)
vec

array([0, 1, 2])

In [ ]:
np.concatenate([vec, vec])

array([0, 1, 2, 0, 1, 2])

In [ ]:
np.hstack([vec, vec])

array([0, 1, 2, 0, 1, 2])

In [ ]:
mat = np.arange(6).reshape(3, 2)
mat

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
np.hstack([mat, mat])

array([[0, 1, 0, 1],
       [2, 3, 2, 3],
       [4, 5, 4, 5]])

In [ ]:
np.concatenate([mat, mat])

array([[0, 1],
       [2, 3],
       [4, 5],
       [0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
np.column_stack([vec, mat])

array([[0, 0, 1],
       [1, 2, 3],
       [2, 4, 5]])

In [ ]:
np.column_stack([vec, vec])

array([[0, 0],
       [1, 1],
       [2, 2]])

In [ ]:
np.vstack([vec, vec])

array([[0, 1, 2],
       [0, 1, 2]])

In [ ]:
np.vstack([mat, mat])

array([[0, 1],
       [2, 3],
       [4, 5],
       [0, 1],
       [2, 3],
       [4, 5]])

**Transpose**

In [ ]:
mat.T

array([[0, 2, 4],
       [1, 3, 5]])

**Slicing**

Taking a part of the array

In [ ]:
mat = np.arange(15).reshape(5, 3)
mat

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [ ]:
mat[:3]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
mat[1:3,:2]

array([[3, 4],
       [6, 7]])

In [ ]:
mat[:, :2]

array([[ 0,  1],
       [ 3,  4],
       [ 6,  7],
       [ 9, 10],
       [12, 13]])

In [ ]:
mat[[3, 0, 1]]

array([[ 9, 10, 11],
       [ 0,  1,  2],
       [ 3,  4,  5]])

In [ ]:
mat[:, 0] % 2 == 1

array([False,  True, False,  True, False])

## **Linear Algebra**

### **Multiplication**

**Vector operations**

In [ ]:
u = np.array([2, 4, 5, 6])

In [ ]:
u * 2

array([ 4,  8, 10, 12])

In [ ]:
v = np.array([1, 0, 0, 2])
v

array([1, 0, 0, 2])

In [ ]:
u + v

array([3, 4, 5, 8])

In [ ]:
u * v

array([ 2,  0,  0, 12])

In [ ]:
v.shape

(4,)

In [ ]:
v.shape[0]

4

In [ ]:
v.shape[1]

IndexError: ignored

**Vector-vector multiplication (dot product)**

In [ ]:
def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0]
    
    n = u.shape[0]
    
    result = 0.0

    for i in range(n):
        result = result + u[i] * v[i]
    
    return result

In [ ]:
vector_vector_multiplication(u, v)

14.0

In [ ]:
u.dot(v)

14

In [ ]:
u = np.array([0, 1, 2])
v = np.array([1, 2, 3])

u.dot(v)

8

**Matrix-vector multiplication**

In [ ]:
U = np.array([
    [2, 4, 5, 6],
    [1, 2, 1, 2],
    [3, 1, 2, 1],
])

In [ ]:
U.shape

(3, 4)

In [ ]:
def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0]
    
    num_rows = U.shape[0]
    
    result = np.zeros(num_rows)
    
    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i], v)
    
    return result

In [ ]:
matrix_vector_multiplication(U, v)

array([14.,  5.,  5.])

In [ ]:
U.dot(v)

array([14,  5,  5])

In [ ]:
X = np.array([
    [0, 1, 2],
    [1, 2, 3],
    [2, 3, 3]
])

In [ ]:
X.dot(u)

array([5, 8, 9])

**Matrix Matrix Multiplication**

In [ ]:
V = np.array([
    [1, 1, 2],
    [0, 0.5, 1], 
    [0, 2, 1],
    [2, 1, 0],
])

In [ ]:
def matrix_matrix_multiplication(U, V):
    assert U.shape[1] == V.shape[0]
    
    num_rows = U.shape[0]
    num_cols = V.shape[1]
    
    result = np.zeros((num_rows, num_cols))
    
    for i in range(num_cols):
        vi = V[:, i]
        Uvi = matrix_vector_multiplication(U, vi)
        result[:, i] = Uvi
    
    return result

In [ ]:
matrix_matrix_multiplication(U, V)


array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [ ]:
U.dot(V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [ ]:
U = np.array([
    [4, 5, 6],
    [5, 6, 7],
    [6, 7, 8]
])

In [ ]:
X.dot(U)

array([[17, 20, 23],
       [32, 38, 44],
       [41, 49, 57]])

**Identity matrix**

In [ ]:
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [ ]:
V.dot(I)

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

## Inverse

To inverse a matrix, use inv function from linalg package

In [ ]:
A = np.array([
    [0, 1, 2],
    [1, 2, 3],
    [2, 3, 3]
])

In [ ]:
Ainv = np.linalg.inv(A)
Ainv

array([[-3.,  3., -1.],
       [ 3., -4.,  2.],
       [-1.,  2., -1.]])

In [ ]:
A.dot(Ainv)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

 When you need to solve Ax = b, you don't really to compute the inverse. You can use solve:

In [ ]:
b = np.array([1, 2, 3])

In [ ]:
x = np.linalg.solve(A, b)
x

array([0., 1., 0.])

In [ ]:
A.dot(x)

array([1., 2., 3.])